[package]
name = "peng_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.107"
libffi = "3.2.0"

[build-dependencies]
bindgen = "0.68.1"
cxx-build = "1.0.107"
